### ISSUE TITLE
类型声明与实际使用无法对应

### ISSUE THREAD

**Issue by NiuGuohui** [fanhaoyuan/vant-weapp-typings#1]
以Button组件为栗子，如果想要响应点击事件必须传入`bindclick` props，但是类型声明中没有这个类型；
有`bind:click`，但是点击button组件不会响应此事件

**Comment by fanhaoyuan** [comment]
是原生小程序使用还是react使用？

**Comment by NiuGuohui** [comment]
> 是原生小程序使用还是react使用？

React+TS

**Comment by fanhaoyuan** [comment]
如果是使用RemaxJS 则应该所有的事件绑定都要省略中间的冒号。[传送](https://remaxjs.org/guide/basic/custom-component#%E8%AF%B7%E6%8C%89%E7%85%A7%E8%87%AA%E5%AE%9A%E4%B9%89%E7%BB%84%E4%BB%B6%E7%9A%84%E5%AE%9A%E4%B9%89%E6%96%B9%E5%BC%8F%E5%A3%B0%E6%98%8E%E5%B1%9E%E6%80%A7%EF%BC%88%E5%B9%B6%E9%9D%9E%E6%89%80%E6%9C%89%E7%BB%84%E4%BB%B6%E9%83%BD%E9%87%87%E7%94%A8%E9%A9%BC%E5%B3%B0%E7%9A%84%E6%96%B9%E5%BC%8F%E5%91%BD%E5%90%8D%E5%B1%9E%E6%80%A7%EF%BC%89%E3%80%82)
之所以之前会如此设定，是因为单纯是按照Vant的配置项去进行声明。而且我在remax v2.15.7 + @vant/weapp 1.9.2中使用`bind:click`是可以使用的🥲
![image](https://user-images.githubusercontent.com/35361626/155936494-9af0cee7-4503-4bcd-9daf-e3984e20c27e.png)

**Comment by NiuGuohui** [comment]
> 如果是使用RemaxJS 则应该所有的事件绑定都要省略中间的冒号。[传送](https://remaxjs.org/guide/basic/custom-component#%E8%AF%B7%E6%8C%89%E7%85%A7%E8%87%AA%E5%AE%9A%E4%B9%89%E7%BB%84%E4%BB%B6%E7%9A%84%E5%AE%9A%E4%B9%89%E6%96%B9%E5%BC%8F%E5%A3%B0%E6%98%8E%E5%B1%9E%E6%80%A7%EF%BC%88%E5%B9%B6%E9%9D%9E%E6%89%80%E6%9C%89%E7%BB%84%E4%BB%B6%E9%83%BD%E9%87%87%E7%94%A8%E9%A9%BC%E5%B3%B0%E7%9A%84%E6%96%B9%E5%BC%8F%E5%91%BD%E5%90%8D%E5%B1%9E%E6%80%A7%EF%BC%89%E3%80%82) 之所以之前会如此设定，是因为单纯是按照Vant的配置项去进行声明。而且我在remax v2.15.7 + @vant/weapp 1.9.2中使用`bind:click`是可以使用的🥲 ![image](https://user-images.githubusercontent.com/35361626/155936494-9af0cee7-4503-4bcd-9daf-e3984e20c27e.png)

好吧，刚发现这个bind的坑
