### ISSUE TITLE
Remaxjs+ts ,使用@vant/weapp ,页面中使用组件，ts报JSX 元素类型“VtButton”不具有任何构造签名或调用签名

### ISSUE THREAD

**Issue by WangXang** [fanhaoyuan/vant-weapp-typings#3]
Remaxjs+ts ,使用@vant/weapp ,页面中使用组件，ts报JSX 元素类型“VtButton”不具有任何构造签名或调用签名

**Comment by fanhaoyuan** [comment]
https://github.com/fanhaoyuan/vant-weapp-typings/tree/master/packages/react-vant-weapp-typings 有设置tsconfig吗

**Comment by fanhaoyuan** [comment]
如果绝对路径不可以 用相对路径寻址到`node_modules/react-vant-weapp-typings`就可以了

**Comment by WangXang** [comment]
是的添加了，依然不行：
![1646988229186](https://user-images.githubusercontent.com/23691331/157832947-adf0be5f-3daf-4eaf-b75b-9e3f94763c74.jpg)

**Comment by fanhaoyuan** [comment]
```ts
//使用
import VantConfigProvider from '@vant/weapp/config-provider';
```

```json
//tsconfig
{
"paths": {
 "@vant/weapp/*": ["./node_modules/react-vant-weapp-typings/dist/*"],
}
}
```

**Comment by fanhaoyuan** [comment]
<img width="873" alt="image" src="https://user-images.githubusercontent.com/35361626/157833730-98d15834-f075-4b97-9805-5022c38ad963.png">
<img width="666" alt="image" src="https://user-images.githubusercontent.com/35361626/157833765-9d04b505-1332-41ee-a388-31f4aa28b7f4.png">

**Comment by WangXang** [comment]
好的，谢谢！
