### ISSUE TITLE
dropdown-item  组件,events类型错误？

### ISSUE THREAD

**Issue by WangXang** [fanhaoyuan/vant-weapp-typings#4]
dropdown-item  组件,events类型错误？remaxjs直接使用change无效 ,
![image](https://user-images.githubusercontent.com/23691331/158301177-1138c589-e82c-4707-991f-d0dfe18bb1f9.png)

**Comment by fanhaoyuan** [comment]
这里确实是类型问题，vant的事件几乎都要加上bind前缀
这会后续修改，或者你pr一个？
