### ISSUE TITLE
Field的type缺少password类型

### ISSUE THREAD

**Issue by mastercbhw** [fanhaoyuan/vant-weapp-typings#54]
![image](https://user-images.githubusercontent.com/23021221/167842751-f9933e08-85ec-48d7-a423-4d42c08b05ea.png)
field的type应该可以设置为任意原生类型。

**Comment by fanhaoyuan** [comment]
这边可能遗漏了，欢迎pr😁

**Comment by fanhaoyuan** [comment]
<img width="1024" alt="image" src="https://user-images.githubusercontent.com/35361626/167975335-4e9d704f-9a21-4483-a966-df0f5e77b31b.png">

`password` 的话是使用这个属性

原生属性遗漏的是`safe-password`和`nickname`
