### ISSUE TITLE
missing step component?

### ISSUE THREAD

**Issue by alex-chan** [fanhaoyuan/vant-weapp-typings#58]
RT

**Comment by alex-chan** [comment]
Can't find step component in src

**Comment by fanhaoyuan** [comment]
Which one are you looking for?

[Stepper](https://github.com/fanhaoyuan/vant-weapp-typings/tree/master/packages/vant-weapp-typings/src/stepper)
[Steps](https://github.com/fanhaoyuan/vant-weapp-typings/tree/master/packages/vant-weapp-typings/src/steps)
