### ISSUE TITLE
remaxjs + ts 怎么安装

### ISSUE THREAD

**Issue by EvanJin** [fanhaoyuan/vant-weapp-typings#61]
pnpm 管理
是直接安装 vant-weapp-typings 还是安装 react-vant-weapp-typings

**Comment by fanhaoyuan** [comment]
安装 `react-vant-weapp-typings`

```bash
pnpm install react-vant-weapp-typings -D
```

然后修改 tsconfig.json 的 paths

```json
{
    "compilerOptions": {
        "baseUrl": ".",
        "paths": {
            "@vant/weapp/*": ["./node_modules/react-vant-weapp-typings/dist/*"]
        }
    }
}
```

**Comment by EvanJin** [comment]
@fanhaoyuan 
![image](https://user-images.githubusercontent.com/1031636/192235848-3ae245b7-6b47-4058-b111-cdadc632c2c6.png)
1) 安装这样的方式引入
![image](https://user-images.githubusercontent.com/1031636/192235937-6b284052-3ee9-45ab-afd1-a17b18147289.png)
还是找不到类型定义
![image](https://user-images.githubusercontent.com/1031636/192236062-e1fcfe43-1b81-4b3b-abd9-4b61b82967fe.png)
2）安装我看之前的issues里面的方式导入
![image](https://user-images.githubusercontent.com/1031636/192236164-2aecbcae-46b3-4fef-8282-184d88fb43ac.png)
可以正常导入
![image](https://user-images.githubusercontent.com/1031636/192236218-5cc01d70-be81-4311-a9ce-39fd3a3f21b4.png)
但是remax的编译就会报错
<img width="851" alt="image" src="https://user-images.githubusercontent.com/1031636/192236565-b9919d65-d6a7-4bcf-ac1f-aa4440ca862e.png">

**Comment by fanhaoyuan** [comment]
因为你需要在 webpack 中的 alias 配置， alias `@vant/weapp/* -> @vant/weapp/dist/*`

**Comment by fanhaoyuan** [comment]
因为 vant 文件目录中是含有 dist 的， ts 路径上是没有 dist，需要适配一下

**Comment by fanhaoyuan** [comment]
或者你 tsconfig 改为下面的样子

```json
{
    "compilerOptions": {
        "baseUrl": ".",
        "paths": {
            "@vant/weapp/dist/*": ["./node_modules/react-vant-weapp-typings/dist/*"]
        }
    }
}
```

**Comment by EvanJin** [comment]
@fanhaoyuan OK, 

> 或者你 tsconfig 改为下面的样子
> 
> ```json
> {
>     "compilerOptions": {
>         "baseUrl": ".",
>         "paths": {
>             "@vant/weapp/dist/*": ["./node_modules/react-vant-weapp-typings/dist/*"]
>         }
>     }
> }
> ```

@fanhaoyuan OK，这种方式是可以解决的，多谢及时回复
